### ISSUE TITLE
Potential performance issue

### ISSUE THREAD

**Issue by tonecool** [ilchenkob/NetRx.Store#1]
For every single change in store collection you're recreating binding source. This can cause performance issues for bigger or more complex collections. Also control which is using it can lost it state (selected item, scroll position...). It would be great if there's a way to bind store collection directly.

DataViewModel.cs
`DataSelectors.Items.Subscribe(items => Items = new ObservableCollection<DataItem>(items));`

**Comment by ilchenkob** [comment]
I'm totally agree with you. But this is just the simple example.
The purpose of this example is just to show the possible way how you can use `NetRx.Store` together with MVVM pattern.
It's up to you how you will implement it in your app.
