### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by aleGuardiola** [ilchenkob/NetRx.Store#2]
Hello, I am about to start a new project and I think this is the perfect state manager that I need but I want to make sure if this project is still in maintenance or what is the future of this project.

**Comment by ilchenkob** [comment]
Hi @aleGuardiola 

Thanks for your interest to this project!
Yes, it's active. I'm, as an author, checking the issue list from time to time.
And I can support you in using this state manager in your project.
If you will have have any problem with it or will need some changes in API, just let me know via creating new ticket.

**Comment by aleGuardiola** [comment]
Very nice thank you
